version: "3.9"
services:
  mymysql:
    container_name: mysql_server
    image: 1yangsh/mymysql:latest
    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mydb
    networks:
      - my-network
  mydjango:
    # deploy:
    #   replicas: 2
    container_name: django_server
    image: 1yangsh/mydjango:latest
    ports:
      - 8000:8000
    depends_on:
      - mymysql
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
